spring.application.name=Sublime
spring.datasource.url=jdbc:mysql://localhost:3306/ventas_sublime
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
jwt.expiration=3600000
jwt.secret=clave_super_secreta_muy_larga_de_32_chars